export const CHANGE_CONTROLS = '[app] CHANGE CONTROLS';
export const CHANGE_CONTROLS_SUCCESS = '[app] CHANGE CONTROLS SUCCESS';

export const FETCH_LANDING = 'FETCH LANDING';
export const FETCH_LANDING_REQUEST = 'FETCH ASSETS REQUEST';
export const FETCH_LANDING_SUCCESS = 'FETCH ASSETS SUCCESS';
export const FETCH_LANDING_FAILURE = 'FETCH ASSETS FAILURE';
