export const CHANGE_CONTROLS = '[app] CHANGE CONTROLS';
export const CHANGE_CONTROLS_SUCCESS = '[app] CHANGE CONTROLS SUCCESS';

export const FETCH_ASSETS = '[app] FETCH ASSETS';
export const FETCH_ASSETS_REQUEST = '[app] FETCH ASSETS REQUEST';
export const FETCH_ASSETS_SUCCESS = '[app] FETCH ASSETS SUCCESS';
export const FETCH_ASSETS_FAILURE = '[app] FETCH ASSETS FAILURE';
