export const CHANGE_CONTROLS = '[app] CHANGE CONTROLS';
export const CHANGE_CONTROLS_SUCCESS = '[app] CHANGE CONTROLS SUCCESS';

export const SEARCH_REQUEST = '[app] SEARCH REQUEST';
export const SEARCH_SUCCESS = '[app] SEARCH SUCCESS';

export const GSA_REQUEST = '[app] GSA REQUEST';
export const GSA_SUCCESS = '[app] GSA SUCCESS';

export const FETCH_ASSETS = '[app] FETCH ASSETS';
export const FETCH_ASSETS_REQUEST = '[app] FETCH ASSETS REQUEST';
export const FETCH_ASSETS_SUCCESS = '[app] FETCH ASSETS SUCCESS';
export const FETCH_ASSETS_FAILURE = '[app] FETCH ASSETS FAILURE';

export const FETCH_DISTRIBUTORS = '[app] FETCH DISTRIBUTORS';
export const FETCH_DISTRIBUTORS_REQUEST = '[app] FETCH DISTRIBUTORS REQUEST';
export const FETCH_DISTRIBUTORS_SUCCESS = '[app] FETCH DISTRIBUTORS SUCCESS';
export const FETCH_DISTRIBUTORS_FAILURE = '[app] FETCH DISTRIBUTORS FAILURE';

export const SEND_MAIL = '[app] SEND MAIL';
export const SEND_MAIL_REQUEST = '[app] SEND MAIL REQUEST';
export const SEND_MAIL_SUCCESS = '[app] SEND MAIL SUCCESS';
export const SEND_MAIL_FAILURE = '[app] SEND MAIL FAILURE';

